# Generated by Django 3.0.7 on 2020-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('positive', models.CharField(max_length=100)),
                ('negative', models.CharField(max_length=100)),
                ('deaths', models.CharField(max_length=100)),
                ('hospitalized', models.CharField(max_length=100)),
            ],
        ),
    ]
